### ISSUE TITLE
Android Studio 2.1.2 open this project have some problem.

### ISSUE THREAD

**Issue by StarRainNight** [cm-heclouds/AndroidSDK#1]
I clone this project,use Android Studio 2.1.2 to open.On the Messages Gradle Sync windows,show the below message:
Error:Gradle version 2.2 is required. Current version is 2.10. If using the gradle wrapper, try editing the distributionUrl in C:\Users\lxy\Desktop\AndroidSDK-master\gradle\wrapper\gradle-wrapper.properties to gradle-2.2-all.zip.

Please fix the project's Gradle settings.
<a href="fixGradleVersionInWrapper">Fix Gradle wrapper and re-import project</a><br><a href="openGradleSettings">Gradle settings</a>

**Comment by chenglei1986** [comment]
This error means your gradle version is not 2.2 but 2.10. So you can open the file "[Project Location]/gradle/wrapper/gradle-wrapper.properties", and modify the **"distributionUrl"** to "https\://services.gradle.org/distributions/gradle-2.10-all.zip". Alternatively you can also download the gradle of right version.

**Comment by chenglei1986** [comment]
@StarRainNight 

This error means your gradle version is not 2.2 but 2.10. So you can open the file "[Project Location]/gradle/wrapper/gradle-wrapper.properties", and modify the **"distributionUrl"** to "https://services.gradle.org/distributions/gradle-2.10-all.zip". Alternatively you can also download the gradle of right version.
