### ISSUE TITLE
竟然没有超时设置，默认只有10秒！10秒真男人啊，兄弟，你是认真的吗？

### ISSUE THREAD

**Issue by hzl512** [cm-heclouds/AndroidSDK#12]
/**
     * 初始化SDK（for HTTPS）
     *
     * @param application Application实例
     * @param debug       是否开启调试模式（打印HTTP请求和响应日志）
     * @param cerString   证书rfc样式输出的字符串
     */
    public static void init(Application application, boolean debug, String cerString) {
        try {
            sAppKey = Meta.readAppKey(application);
            Urls.sScheme = Meta.readScheme(application);
            Urls.sHost = Meta.readHost(application);
        } catch (Exception e) {
            e.printStackTrace();
        }

        sDebug = debug;

        OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder()
                ;
        if (sDebug) {
            HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor(new OneNetLogger());
            loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
            okHttpClientBuilder.addNetworkInterceptor(loggingInterceptor);
        }
        okHttpClientBuilder.addInterceptor(sApiKeyInterceptor);

        if (!TextUtils.isEmpty(cerString)) {
            try {
                CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
                Collection<? extends Certificate> certificates = certificateFactory.generateCertificates(new Buffer().writeUtf8(cerString).inputStream());
                if (null == certificates || certificates.isEmpty()) {
                    throw new IllegalArgumentException("expected non-empty set of trusted certificates");
                }

                char[] password = "password".toCharArray();
                KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
                keyStore.load(null, password);

                int index = 0;
                for (Certificate certificate : certificates) {
                    String certificateAlias = Integer.toString(index++);
                    keyStore.setCertificateEntry(certificateAlias, certificate);
                }

                KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
                keyManagerFactory.init(keyStore, password);
                TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
                trustManagerFactory.init(keyStore);
                TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
                if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
                    throw new IllegalStateException("Unexpected default trust managers:" + Arrays.toString(trustManagers));
                }

                SSLContext sslContext = SSLContext.getInstance("TLS");
                sslContext.init(null, trustManagers, null);
                SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();

                okHttpClientBuilder.sslSocketFactory(sslSocketFactory, (X509TrustManager) trustManagers[0]);
            } catch (CertificateException e) {
                e.printStackTrace();
            } catch (KeyStoreException e) {
                e.printStackTrace();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } catch (UnrecoverableKeyException e) {
                e.printStackTrace();
            } catch (KeyManagementException e) {
                e.printStackTrace();
            }
        }

        sHttpExecutor = new HttpExecutor(okHttpClientBuilder.build());
    }
  

  /**
     * Sets the default connect timeout for new connections. A value of 0 means no timeout,
     * otherwise values must be between 1 and {@link Integer#MAX_VALUE} when converted to
     * milliseconds.
     *
     * <p>The connectTimeout is applied when connecting a TCP socket to the target host.
     * The default value is 10 seconds.
     */
    public Builder connectTimeout(long timeout, TimeUnit unit) {
      connectTimeout = checkDuration("timeout", timeout, unit);
      return this;
    }

**Comment by chenglei1986** [comment]
@hzl512 对于手机客户端来讲，10秒钟没有收到响应或者两个数据包的时间间隔超过10秒，基本可以断定为网络问题。如果排除网络问题，那么就是服务端有严重的性能问题，也没有理由让用户等待。默认10秒理论上是没有问题的。

**Comment by hzl512** [comment]
怎么说呢，物联网设备使用的是网络，特别是车辆的情况，经常网络不大好，这个基本是用户自行执行的htpp上传，设置有超时比较好，至少可以设置，不是么。

**Comment by chenglei1986** [comment]
@hzl512 这个SDK不是给设备用的，是手机端开发app用的，只与OneNET后台交互。后面我新增一个设置超时的接口吧。

**Comment by hzl512** [comment]
好的，谢谢，最好也能做一下失败多少次，重试几次那种。
