### ISSUE TITLE
一直返回auth failed

### ISSUE THREAD

**Issue by q805699513** [cm-heclouds/AndroidSDK#14]

**Comment by q805699513** [comment]
{"errno":3,"error":"auth failed"}
api-key:这个参数开发者后台没有找到

**Comment by chenglei1986** [comment]
![](https://ftp.bmp.ovh/imgs/2019/11/93b7bfc70dc52854.png)
![](https://ftp.bmp.ovh/imgs/2019/11/ca127b9934c913c1.png)

**Comment by chenglei1986** [comment]
[https://open.iot.10086.cn/develop/global/product/#/console](https://open.iot.10086.cn/develop/global/product/#/console)控制台点击我创建的产品，查看Master-APIkey

**Comment by q805699513** [comment]
mqtt物联网套件后台里的产品好像没有这个Master-APIkey。
