### ISSUE TITLE
eclipse 怎么导入AndroidSDK-master 到自己的项目中，求大神指点

### ISSUE THREAD

**Issue by seagullanddog** [cm-heclouds/AndroidSDK#2]

**Comment by chenglei1986** [comment]
V1版本可以通过拷贝源码到eclipse的src目录解决，V2版本由于依赖关系复杂，使用eclipse很困难，Google已经停止了对eclipse的ADT支持，意味着可能无法使用高版本SDK，开发出的程序在高版本手机上有无法使用的可能。建议早日切换到Android Studio。

**Comment by chenglei1986** [comment]
@seagullanddog 你可以尝试把okhttp、okio和logging-interceptor三个jar下载下来，至少保证SDK部分能用，示例app也可以尝试将app/build.gradle中的库导入

[https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp](https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp)
[https://mvnrepository.com/artifact/com.squareup.okio/okio](https://mvnrepository.com/artifact/com.squareup.okio/okio)
[https://mvnrepository.com/artifact/com.squareup.okhttp3/logging-interceptor](https://mvnrepository.com/artifact/com.squareup.okhttp3/logging-interceptor)
