### ISSUE TITLE
AndroidSDK-master 这个sdk里面的函数怎么使用，该怎么看，是否有例子

### ISSUE THREAD

**Issue by seagullanddog** [cm-heclouds/AndroidSDK#5]
这个AndroidSDK里面的public static void queryDataPoints(String deviceId, Map<String, String> params, OneNetApiCallback callback)这个函数怎么使用，本人接触Android不久，有大神引用过这个函数的例子么，如果有的话，能否借鉴一下，顺便教我怎么看懂里面的函数，将感激不尽

**Comment by chenglei1986** [comment]
@seagullanddog 在这里
[https://github.com/cm-heclouds/AndroidSDK/blob/master/app/src/main/java/com/chinamobile/iot/onenet/sdksample/fragment/ApiTestFragment.java](https://github.com/cm-heclouds/AndroidSDK/blob/master/app/src/main/java/com/chinamobile/iot/onenet/sdksample/fragment/ApiTestFragment.java) 第670行

具体参数的含义可以结合文档[http://www.heclouds.com/doc/art260.html#68](http://www.heclouds.com/doc/art260.html#68)一起看
