### ISSUE TITLE
AndroidSDK项目文档写的不知怎么入手啊

### ISSUE THREAD

**Issue by wu-leaf** [cm-heclouds/AndroidSDK#7]
AndroidSDK项目文档写的不知怎么入手啊，求更详细的使用文档说明

**Comment by chenglei1986** [comment]
我认为你不是要Android SDK的文档，而是OneNET RESTful API的文档

**Comment by wu-leaf** [comment]
请问，我在OneNet上创建了项目（环境数据采集类），现在想在安卓手机上获取硬件上传到 OneNet 后台的数据，我不是应该使用这个 AndroidSDK 吗？？？

**Comment by chenglei1986** [comment]
是的，调用`OneNetApi.queryDataPoints()`方法即可

**Comment by wu-leaf** [comment]
可以留个联系方式吗？关于 AndroidSDK 的具体使用，我还有问题想请教

**Comment by chenglei1986** [comment]
@wu-leaf 发你邮箱了

**Comment by wu-leaf** [comment]
@chenglei1986 你好，没收到你的邮件啊

**Comment by chenglei1986** [comment]
不是veyron_gz@163.com这个吗？

**Comment by chenglei1986** [comment]
直接贴在这里吧，应该没啥，QQ：282322455
