### ISSUE TITLE
Android studio如何集成sdk？

### ISSUE THREAD

**Issue by badwi5** [cm-heclouds/AndroidSDK#8]
按照wiki的教程来报错Project with path ':onenet-sdk' could not be found in project ':app'，sdk是直接拷到项目的总目录下吗，compile project(':onenet-sdk')和compile 'com.chinamobile.iot.onenet:onenet-sdk:+'这两句分别要写在哪个build.gradle中？

**Comment by chenglei1986** [comment]
直接在你App的build.gradle里加上compile 'com.chinamobile.iot.onenet:onenet-sdk:+'就可以了，不用拷贝代码

**Comment by badwi5** [comment]
请问android sdk有没有实现批量查询设备状态或者批量查询设备最新数据的方法

**Comment by chenglei1986** [comment]
现在还没有
