### ISSUE TITLE
获取datapoint的查询url错误

### ISSUE THREAD

**Issue by fafa6** [cm-heclouds/AndroidSDK#9]
在 DataPoint.class 中，查询的url路径最后漏掉了datapoints，导致调用OneNetApi.queryDataPoints接口时，会出错。
`public static String urlForQuerying(String deviceId, Map<String, String> params) {
        HttpUrl.Builder builder = new HttpUrl.Builder().scheme(Urls.SCHEME).host(Urls.sHost)
                .addPathSegment("devices").addPathSegment(deviceId);`

**Comment by chenglei1986** [comment]
@fafa6 这个问题6月份就修复了，你更新下代码呢

**Comment by chenglei1986** [comment]
@fafa6 谢谢提醒，已修改
